version: 0.2


   
phases:
  build:
    commands:
      -/katalon/katalon/source katalonstudio/katalon katalon-execute.sh -apiKey=9b26b1f9-8b64-4c42-b5d9-1583bf3ae781 -browserType="Chrome" -retry=0 -statusDelay=15 -testSuitePath="Test Suites/TS_RegressionTest"
artifacts:
  files:
    - report/*
reports: #New
  KatalonTestReports: # CodeBuild will create a report group called "KatalonTetReport".
    files: #Store all of the files
      - 'report/JUnit_Report.xml'


